/** Default Rwanda destinations seeded when the table is empty. */
export const DEFAULT_DESTINATION_SEEDS = [
  {
    name: 'Volcanoes National Park',
    slug: 'volcanoes-national-park',
    category: 'parks',
    description:
      'Home to the magnificent mountain gorillas. Experience once-in-a-lifetime gorilla trekking in their natural habitat.',
    location: 'Northern Province, Rwanda',
    distance: '2.5 hours from Kigali',
    permitRequired: true,
    permitPrice: 1500,
    highlights: [
      'Mountain gorilla trekking',
      'Golden monkey tracking',
      'Dian Fossey grave visit',
    ],
    activities: [
      { name: 'Gorilla Trekking', icon: '🦍', description: 'One-hour interaction with mountain gorillas in the wild' },
      { name: 'Golden Monkey Tracking', icon: '🐵', description: 'Track and observe playful golden monkeys' },
    ],
    bestTime: 'June–September, December–February',
    weather: 'Mountain climate: 10–20°C',
    reviews: [{ name: 'Sarah K.', rating: 5, comment: 'Unforgettable gorilla experience!' }],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Yes — all tours are led by licensed guides who prioritize your safety.' },
      { question: 'How many days should I spend here?', answer: 'We recommend 2–3 days to fully experience gorilla trekking and nearby attractions.' },
    ],
    lat: -1.442,
    lng: 29.626,
  },
  {
    name: 'Akagera National Park',
    slug: 'akagera-national-park',
    category: 'parks',
    description:
      "Rwanda's largest national park, home to the Big Five and diverse wildlife. Perfect for game drives and boat safaris.",
    location: 'Eastern Province, Rwanda',
    distance: '2.5 hours from Kigali',
    permitRequired: false,
    permitPrice: 0,
    highlights: ['Big Five safari', 'Boat rides on Lake Ihema', 'Bird watching'],
    activities: [
      { name: 'Game Drives', icon: '🦁', description: 'Spot the Big Five on safari drives' },
      { name: 'Boat Safari', icon: '🚤', description: 'Cruise Lake Ihema' },
    ],
    bestTime: 'June–September',
    weather: 'Warm climate: 20–30°C',
    reviews: [{ name: 'Emma L.', rating: 5, comment: 'Saw all Big Five! Amazing experience.' }],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Yes — park rangers and guides accompany all safari activities.' },
      { question: 'How many days should I spend here?', answer: '2–3 days is ideal for game drives and boat safaris.' },
    ],
    lat: -1.583,
    lng: 30.733,
  },
  {
    name: 'Nyungwe Forest',
    slug: 'nyungwe-forest',
    category: 'parks',
    description:
      'Ancient montane rainforest with 13 primate species, canopy walkway, and diverse birdlife.',
    location: 'Southwestern Rwanda',
    distance: '5 hours from Kigali',
    permitRequired: true,
    permitPrice: 90,
    highlights: ['Chimpanzee tracking', 'Canopy walkway', 'Waterfall hikes'],
    activities: [
      { name: 'Canopy Walk', icon: '🌉', description: 'Walk 160m above the forest floor' },
    ],
    bestTime: 'June–September',
    weather: 'Cool and humid: 10–18°C',
    reviews: [],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Yes — trails are maintained and guided walks are standard.' },
      { question: 'How many days should I spend here?', answer: '2–4 days to enjoy chimp tracking and canopy walks.' },
    ],
    lat: -2.483,
    lng: 29.217,
  },
  {
    name: 'Kigali City',
    slug: 'kigali-city',
    category: 'cities',
    description:
      "Rwanda's clean and vibrant capital city. Rich history, culture, and modern development.",
    location: 'Central Rwanda',
    distance: 'Capital city',
    permitRequired: false,
    permitPrice: 0,
    highlights: ['Genocide Memorial', 'Inema Arts Center', 'Local markets'],
    activities: [],
    bestTime: 'Year-round',
    weather: 'Pleasant climate: 18–27°C',
    reviews: [],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Kigali is one of Africa\'s safest capital cities for visitors.' },
      { question: 'How many days should I spend here?', answer: '1–2 days for city tours before or after your safari.' },
    ],
    lat: -1.944,
    lng: 30.061,
  },
  {
    name: 'Lake Kivu',
    slug: 'lake-kivu',
    category: 'lakes',
    description:
      "Rwanda's largest lake, nestled between mountains. Perfect for relaxation and water sports.",
    location: 'Western Rwanda',
    distance: '3–4 hours from Kigali',
    permitRequired: false,
    permitPrice: 0,
    highlights: ['Lakeside resorts', 'Boat tours', 'Hot springs'],
    activities: [],
    bestTime: 'Year-round',
    weather: 'Mild climate: 18–25°C',
    reviews: [],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Yes — lakeside towns are welcoming and well serviced.' },
      { question: 'How many days should I spend here?', answer: '2–3 days for relaxation between park visits.' },
    ],
    lat: -2.0,
    lng: 29.35,
  },
  {
    name: 'Gishwati-Mukura',
    slug: 'gishwati-mukura',
    category: 'parks',
    description:
      "Rwanda's newest national park — forest conservation and chimpanzee habitat.",
    location: 'Western Rwanda',
    distance: '3 hours from Kigali',
    permitRequired: true,
    permitPrice: 90,
    highlights: ['Chimpanzee habituation', 'Forest hiking', 'Bird watching'],
    activities: [],
    bestTime: 'June–September',
    weather: 'Cool mountain climate: 12–20°C',
    reviews: [],
    faqs: [
      { question: 'Is this destination safe to visit?', answer: 'Guided forest walks ensure a safe experience.' },
      { question: 'How many days should I spend here?', answer: '1–2 days combined with Lake Kivu works well.' },
    ],
    lat: -1.75,
    lng: 29.45,
  },
]
